version: '3.8'
services:
  wandel-pro:
    build: .
    image: ghcr.io/blankf/wandelbadge-app:latest
    ports:
      - "7000:3000"
    volumes:
      - wandel-data:/usr/src/app/data
    restart: always

volumes:
  wandel-data: