version: '3.8'
services:
  wandel-pro:
    build: .
    image: ghcr.io/blankf/wandelbadge-app:latest
    ports:
      - "7000:3000"
    environment:
      - ENABLE_SCRAPER=true  # Set to 'false' to hide the Home Assistant scraper tab
    volumes:
      - /home/blankf/work/personal/wandelapp/data:/usr/src/app/data
    restart: always

volumes:
  wandel-data:
